# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thmsmlr
email: millar.thomas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  the digital graveyard for my thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thmsmlr.com" # the base hostname & protocol for your site
twitter_username: thmsmlr
github_username:  thmsmlr
permalink: "/posts/:title"

# Build settings
markdown: kramdown
exclude: [deploy]
